on:
  workflow_dispatch:
  push:

name: tuic-client

jobs:
  push_to_registry:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            version: 1.0.0

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./
          platforms: |
            linux/386
            linux/amd64
            linux/arm/v7
            linux/arm64
          push: true
          build-args: |
            VERSION=${{ matrix.version }}
          tags: |
            kilvn/tuic-client:latest
            kilvn/tuic-client:${{ matrix.version }}
